---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
  - name: i want to install webserver on ubuntunode
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"
  - name: install webserver on RedHat
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"
  - name: i want to install webserver on RedHatnode
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"